# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34cf6a1566a1c7169cea3e1dbb01eb7e101cab088efca4de09cd52331a5aeda625a5ad3b979b5257496a3d3c580e41bead59b67ab49dd9c0520e1a42d91947e4

test:
  secret_key_base: ae7ed78975554bfd1b1ecf7c6ccd768c0a6274d19ffadfdd59a969fb72e3969176db5d68b561edaef95b5de99a92ae3cc835e507ab092e3cbd44af62b88d8abf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
